on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: benchmark

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1
  # Pin the nightly toolchain to prevent breakage.
  # This should be occasionally updated.
  RUST_NIGHTLY_TOOLCHAIN: nightly-2021-03-08

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      rust-versions: ${{ steps.definitions.outputs.versions }}
      msrv: ${{ steps.definitions.outputs.msrv }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Flamegraph
        run: cargo install flamegraph
      - name: Evaluate definitions
        id: definitions
        run: |
          export MSRV=$(cat rust-toolchain | awk '{$1=$1};1')
          echo "::set-output name=msrv::$MSRV"
          export RAW_VERSIONS="stable beta $RUST_NIGHTLY_TOOLCHAIN $MSRV"
          export VERSIONS=$(echo $RAW_VERSIONS | jq -scR 'rtrimstr("\n")|split(" ")|.')
          echo "::set-output name=versions::$VERSIONS"

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: ${{ env.RUST_NIGHTLY_TOOLCHAIN }}
          profile: minimal
          override: true
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./target/criterion
          key: ${{ runner.os }}-benchmark
      # GHA-benchmark needs the original bencher format to read results.
      # see https://github.com/rhysd/github-action-benchmark/issues/35
      - name: Run benchmark
        run: cargo bench --bench my_benchmark -- --output-format bencher | tee output.txt

      - name: "Continuous Benchmark"
        uses: rhysd/github-action-benchmark@v1.8.1
        with:
          tool: 'cargo'
          output-file-path: output.txt
          fail-on-alert: true
          external-data-json-path: target/criterion/fib20slow/base/benchmark.json
